version: '3.9'
services:
  maria-db-1:
    container_name: sunet-mdb1
    image: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=userp@ssword
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud

  maria-db-2:
    container_name: sunet-mdb2
    image: mariadb
    ports:
      - "3307:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=userp@ssword
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud

  ssp-mdb:
    container_name: sunet-ssp-mdb
    image: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=$$puser
      - MYSQL_USER=sspuser
      - MYSQL_DATABASE=saml

  base-app:
    build: 
      context: apache-php
      # these line should be comment if you does not use http pondersource proxy
      args:
        HTTP_PROXY: http://172.17.0.1:1110
        HTTPS_PROXY: http://172.17.0.1:1110
        NO_PROXY: localhost,127.0.0.0/8,::1
    image: apache-php:latest
    deploy:
      mode: replicated
      replicas: 0
  
  ssp-saml:
    container_name: "sunet-ssp-idp"
    build: 
      context: SSP
      # these line should be comment if you does not use http pondersource proxy
      args:
        HTTP_PROXY: http://172.17.0.1:1110
        HTTPS_PROXY: http://172.17.0.1:1110
        NO_PROXY: localhost,127.0.0.0/8,::1
    image: ponder-ssp:latest
    ports:
      - 8082:80

  nextcloud1.local:
    container_name: sunet.nextcloud.first
    tty: true
    depends_on: 
      - base-app
      - maria-db-1
    build: 
      context: nextcloud
      # these line should be comment if you does not use http pondersource proxy
      args:
        HTTP_PROXY: http://172.17.0.1:1110
        HTTPS_PROXY: http://172.17.0.1:1110
        NO_PROXY: localhost,127.0.0.0/8,::1
    image: "sunet-nextcloud"
    ports:
      - "8080:80"
  
  nextcloud2.local:
    container_name: sunet.nextcloud.second
    tty: true
    depends_on: 
      - base-app
      - maria-db-2
    image: "sunet-nextcloud"
    ports:
      - "8081:80"
  
  firefox-tester:
    container_name: sunet-tester
    image: jlesage/firefox:v1.17.1
    ports:
      - 5800:5800
    shm_size: '2gb'
    volumes:
      - /tmp/shm:/config:rw
