version: '3.9'
networks:
  testnet:

services:
  maria-db-1:
    container_name: sunet-mdb1
    image: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=userp@ssword
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
    networks:
      - testnet

  maria-db-2:
    container_name: sunet-mdb2
    image: mariadb
    ports:
      - "3307:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=userp@ssword
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
    networks:
      - testnet

  base-app:
    build: 
      context: apache-php
      # these line should be commented out if you does not use the pondersource http proxy
      # args:
      #   HTTP_PROXY: http://172.17.0.1:1110
      #   HTTPS_PROXY: http://172.17.0.1:1110
      #   NO_PROXY: localhost,127.0.0.0/8,::1
    image: apache-php:latest
    deploy:
      mode: replicated
      replicas: 0
    networks:
      - testnet

  nextcloud-1:
    container_name: sunet-nc1
    tty: true
    depends_on: 
      - base-app
      - maria-db-1
    build: 
      context: nextcloud
      # these line should be commented if you does not use the pondersource http proxy
      # args:
      #   HTTP_PROXY: http://172.17.0.1:1110
      #   HTTPS_PROXY: http://172.17.0.1:1110
      #   NO_PROXY: localhost,127.0.0.0/8,::1
    image: "sunet-nextcloud"
    ports:
      - "80:80"
    networks:
      - testnet
  
  nextcloud-2:
    container_name: sunet-nc2
    tty: true
    depends_on: 
      - base-app
      - maria-db-2
    image: "sunet-nextcloud"
    ports:
      - "80:80"
    networks:
      - testnet

  firefox-tester:
    container_name: sunet-tester
    image: jlesage/firefox:v1.17.1
    ports:
      - 5800:5800
    shm_size: '2gb'
    volumes:
      - /tmp/shm:/config:rw
    networks:
      - testnet
