version: '3.9'
services:
  maria-db-1:
    container_name: mariadb-1
    image: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=userp@ssword
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud

  maria-db-2:
    container_name: mariadb-2
    image: mariadb
    ports:
      - "3307:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=r00tp@$$word
      - MYSQL_PASSWORD=userp@ssword
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud

  base-app:
    build: 
      context: apache-php
    image: apache-php:latest
    deploy:
      mode: replicated
      replicas: 0
  
  nextcloud-1:
    container_name: nextcloud-1
    tty: true
    depends_on: 
      - base-app
      - maria-db-1
    build: 
      context: nextcloud
    image: "sunet-nextcloud"
    ports:
      - "8080:80"
  
  nextcloud-2:
    container_name: nextcloud-2
    tty: true
    depends_on: 
      - base-app
      - maria-db-2
    build: 
      context: nextcloud
    image: "sunet-nextcloud"
    ports:
      - "8081:80"



