version: '3.9'
networks:
  testnet:

services:
  sunet-mdb1:
    container_name: sunet-mdb1
    image: mariadb
    ports:
      - "3306:3306"
    environment: 
      - MARIADB_ROOT_PASSWORD=r00tp@$$word
      - MARIADB_PASSWORD=userp@ssword
      - MARIADB_USER=nextcloud
      - MARIADB_DATABASE=nextcloud
    networks:
      - testnet

  sunet-mdb2:
    container_name: sunet-mdb2
    image: mariadb
    ports:
      - "3307:3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    environment: 
      - MARIADB_ROOT_PASSWORD=r00tp@$$word
      - MARIADB_PASSWORD=userp@ssword
      - MARIADB_USER=nextcloud
      - MARIADB_DATABASE=nextcloud
    networks:
      - testnet

  # only to be built, deploying zero replicas:
  base-app:
    build: 
      context: apache-php
    image: apache-php:latest
    deploy:
      mode: replicated
      replicas: 0

  sunet-nc1:
    container_name: sunet-nc1
    tty: true
    depends_on: 
      - base-app
      - sunet-mdb-1
    build: 
      context: sunet-nextcloud
    image: "sunet-nextcloud"
    ports:
      - "8080:80"
    networks:
      - testnet
  
  sunet-nc2:
    container_name: sunet-nc2
    tty: true
    depends_on: 
      - base-app
      - sunet-mdb-2
    image: "sunet-nextcloud"
    ports:
      - "8081:80"
    networks:
      - testnet

  firefox-tester:
    container_name: sunet-tester
    image: jlesage/firefox:v1.17.1
    ports:
      - 5800:5800
    shm_size: '2gb'
    volumes:
      - /tmp/shm:/config:rw
    networks:
      - testnet
